### PR TITLE
chore: bump monero-core-cpp to apply fee estimation

### PR DESCRIPTION
**Pull request by thanhdanh**
# Summary
- Bump the [mymonero-core-cpp](https://github.com/ExodusMovement/mymonero-core-cpp/pull/34) with new fee estimation.
- Re-compile code from C++ to js. 

Checksum:
```
79626c74f84ee640b90a0f765ac5cd6e99d17caf7dd7d31a5db392ecacda39e4  monero_utils/MyMoneroCoreCpp_WASM.js
301f828c7c27c821ba6f355d536f45796d82bd93556ae99c8d7ed972f92e5bc5  monero_utils/MyMoneroCoreCpp_WASM.wasm
```

# How to test
- Require docker is installed.
- Run the following commands:
```
./prepare.sh
./build.sh
shasum -a 256 monero_utils/MyMoneroCoreCpp_*
```
- Compare the checksum.

### CODE REVIEW

**Review by gutenye — COMMENTED** [review]
needs audit

**Comment by farisissa8** [comment]
Did not audit. I just wanted to confirm build shas. I also got:

```
79626c74f84ee640b90a0f765ac5cd6e99d17caf7dd7d31a5db392ecacda39e4  monero_utils/MyMoneroCoreCpp_WASM.js
301f828c7c27c821ba6f355d536f45796d82bd93556ae99c8d7ed972f92e5bc5  monero_utils/MyMoneroCoreCpp_WASM.wasm
```

**Comment by 633kh4ck** [comment]
Audit scope: https://github.com/ExodusMovement/mymonero-core-cpp/compare/4f4a013ab3bad790c53cfdac6f8703d6f4935924..b0412c3054e2edb5bba7b6ac5bc9c941fa62d3e0.

**Comment by thanhdanh** [comment]
Hi @farisissa8 , could I merge this PR? And after it's merged, please help me to build an official version of it. Thanks. (cc: @feri42 )

**Comment by farisissa8** [comment]
@RyanZim @gutenye what do you think about the following:

Since the build is deterministic and won't be built on a dedicated machine, I don't think we need to wait to merge this anymore. The audit can happen on the platforms like any other PR. Which means as long as someone confirms determinism on this PR (I did above), I don't see why @thanhdanh shouldn't be able to just merge, publish the new version, bring it to desktop and the audit is kicked off there with the normal flow.

**Comment by gutenye** [comment]
@farisissa8 sounds good

**Review by feri42 — APPROVED** [review]
utACK

**Comment by 633kh4ck** [comment]
Posting for transparency. Methodology I followed here:
- cursory [scope](https://github.com/ExodusMovement/mymonero-core-js/pull/55#issuecomment-1715657478) review;
- build reproduction.

Checksums:
```
79626c74f84ee640b90a0f765ac5cd6e99d17caf7dd7d31a5db392ecacda39e4  monero_utils/MyMoneroCoreCpp_WASM.js
301f828c7c27c821ba6f355d536f45796d82bd93556ae99c8d7ed972f92e5bc5  monero_utils/MyMoneroCoreCpp_WASM.wasm
```

**Pull request merged**
