### PR TITLE
initUtils helper which works with webpack

### PR DESCRIPTION
**Pull request by headfire94**
I can use this helper inside exodus and bundle it with webpack instead of copy node_modules

### CODE REVIEW

**Comment by headfire94** [comment]
@ChALkeR need your help. When i bundle this module inside exodus (https://github.com/ExodusMovement/exodus-desktop/tree/egor/bundle-monero-with-webpack)

I got this error due to our security settings `Content-Security-Policy` 
```
...build/Exodus-darwin-x64/Exodus.app/Contents/Resources/app.asar/src/app/vendors.js:949192 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```
(btw it works fine when i use webpack in dev mode and run app exodus_dev.html with other security settings):

What can I change here to prevent it?

**Comment by gutenye** [comment]
@headfire94 I pushed some fixes along with add `index.electron.js`  file

**Comment by gutenye** [comment]
Tested on dev, send and receive XMR, refresh XMR.
For production, wait for the fix.

**Review by Sekhmet — APPROVED** [review]
utACK

**Comment by olistic** [comment]
@ChALkeR ping!

**Comment by headfire94** [comment]
PR needed to fix this issue https://github.com/ExodusMovement/exodus-desktop/issues/5024.
Close due inactivity

**Comment by ChALkeR** [comment]
Will investigate from here, sorry for missing this.
Needs some work first though on reorganizing the code at the consuming side.

**Comment by ChALkeR** [comment]
This was already solved downstream, let's close for now.

**Comment by ChALkeR** [comment]
Replaced with https://github.com/ExodusMovement/mymonero-core-js/pull/29.

**Pull request closed without merging**
